version: 1.0'

services:

db:
  image: mysql:8.3.0
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: audiobookService
  ports: "33062:3306"

mysql_gleb:
  image: mysql_image_gleb:1.0
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: audiobookService
  ports: "33062:3306"
